from models.movie import Movie
from uuid import uuid4

example_movies: list[Movie] = [
    Movie(
        id=uuid4(),
        title="Avatar",
        rated="PG-13",
        release="18 Dec 2009",
        image="http://ia.media-imdb.com/images/M/MV5BMTYwOTEwNjAzMl5BMl5BanBnXkFtZTcwODc5MTUwMw@@._V1_SX300.jpg",
    ),
    Movie(
        id=uuid4(),
        title="I Am Legend",
        rated="PG-13",
        release="14 Dec 2007",
        image="http://ia.media-imdb.com/images/M/MV5BMTU4NzMyNDk1OV5BMl5BanBnXkFtZTcwOTEwMzU1MQ@@._V1_SX300.jpg",
    ),
    Movie(
        id=uuid4(),
        title="300",
        rated="R",
        release="09 Mar 2007",
        image="http://ia.media-imdb.com/images/M/MV5BMjAzNTkzNjcxNl5BMl5BanBnXkFtZTYwNDA4NjE3._V1_SX300.jpg",
    ),
    Movie(
        id=uuid4(),
        title="The Avengers",
        rated="PG-13",
        release="04 May 2012",
        image="http://ia.media-imdb.com/images/M/MV5BMTk2NTI1MTU4N15BMl5BanBnXkFtZTcwODg0OTY0Nw@@._V1_SX300.jpg",
    ),
    Movie(
        id=uuid4(),
        title="The Wolf of Wall Street",
        rated="R",
        release="25 Dec 2013",
        image="http://ia.media-imdb.com/images/M/MV5BMjIxMjgxNTk0MF5BMl5BanBnXkFtZTgwNjIyOTg2MDE@._V1_SX300.jpg",
    ),
    Movie(
        id=uuid4(),
        title="Interstellar",
        rated="PG-13",
        release="07 Nov 2014",
        image="http://ia.media-imdb.com/images/M/MV5BMjIxNTU4MzY4MF5BMl5BanBnXkFtZTgwMzM4ODI3MjE@._V1_SX300.jpg",
    ),
    Movie(
        id=uuid4(),
        title="Game of Thrones",
        rated="TV-MA",
        release="17 Apr 2011",
        image="http://ia.media-imdb.com/images/M/MV5BMjM5OTQ1MTY5Nl5BMl5BanBnXkFtZTgwMjM3NzMxODE@._V1_SX300.jpg",
    ),
    Movie(
        id=uuid4(),
        title="Vikings",
        rated="TV-14",
        release="03 Mar 2013",
        image="http://ia.media-imdb.com/images/M/MV5BOTEzNzI3MDc0N15BMl5BanBnXkFtZTgwMzk1MzA5NzE@._V1_SX300.jpg",
    ),
    Movie(
        id=uuid4(),
        title="Gotham",
        rated="TV-14",
        release="01 Aug 2014",
        image="http://ia.media-imdb.com/images/M/MV5BMTY2MjMwNDE4OV5BMl5BanBnXkFtZTgwNjI1NjU0OTE@._V1_SX300.jpg",
    ),
    Movie(
        id=uuid4(),
        title="Power",
        rated="TV-MA",
        release="N/A",
        image="http://ia.media-imdb.com/images/M/MV5BOTA4NTkzMjUzOF5BMl5BanBnXkFtZTgwNzg5ODkxOTE@._V1_SX300.jpg",
    ),
    Movie(
        id=uuid4(),
        title="Narcos",
        rated="TV-MA",
        release="28 Aug 2015",
        image="http://ia.media-imdb.com/images/M/MV5BMTU0ODQ4NDg2OF5BMl5BanBnXkFtZTgwNzczNTE4OTE@._V1_SX300.jpg",
    ),
    Movie(
        id=uuid4(),
        title="Breaking Bad",
        rated="TV-14",
        release="20 Jan 2008",
        image="http://ia.media-imdb.com/images/M/MV5BMTQ0ODYzODc0OV5BMl5BanBnXkFtZTgwMDk3OTcyMDE@._V1_SX300.jpg",
    ),
    Movie(
        id=uuid4(),
        title="Doctor Strange",
        rated="N/A",
        release="04 Nov 2016",
        image="http://ia.media-imdb.com/images/M/MV5BNjgwNzAzNjk1Nl5BMl5BanBnXkFtZTgwMzQ2NjI1OTE@._V1_SX300.jpg",
    ),
    Movie(
        id=uuid4(),
        title="Assassin's Creed",
        rated="N/A",
        release="21 Dec 2016",
        image="http://ia.media-imdb.com/images/M/MV5BMTU2MTQwMjU1OF5BMl5BanBnXkFtZTgwMDA5NjU5ODE@._V1_SX300.jpg",
    ),
    Movie(
        id=uuid4(),
        title="Luke Cage",
        rated="TV-MA",
        release="30 Sep 2016",
        image="http://ia.media-imdb.com/images/M/MV5BMTcyMzc1MjI5MF5BMl5BanBnXkFtZTgwMzE4ODY2OTE@._V1_SX300.jpg",
    ),
]
